### ISSUE TITLE
Github actions to make windows exe - Help wanted

### ISSUE THREAD

**Issue by Beherith** [Beherith/springrts_smf_compiler#22]
Ive been using "pyinstaller --onefile" to create the exe, but this is far from ideal and unfun. Help appreciated!

**Comment by Beherith** [comment]
Cool, this is almost done, only gotta figure out how to package everything and release on each build...

**Comment by ghost** [comment]
Solved in https://github.com/Beherith/springrts_smf_compiler/pull/28
