### ISSUE TITLE
Can't find pymapconv.exe

### ISSUE THREAD

**Issue by NobodyVII** [Beherith/springrts_smf_compiler#30]
The description says "launch the precompiled version in pymapconv.exe in this repository", but I can't find this exe... there is only the pymapconv.py in the repository...

**Comment by ghost** [comment]
There is a release pipeline for this repo now, but the docs are a bit out of date.
If you want to grab the precompiled release, grab it off of releases [here](https://github.com/Beherith/springrts_smf_compiler/releases).
