### ISSUE TITLE
problem installing precompiled version for Windows

### ISSUE THREAD

**Issue by Xendergo** [Beherith/springrts_smf_compiler#9]
When I run the MSI and select a file path to install in, it throws the error: "The folder path 'SMF compiler/decompiler' contains an invalid character"

I'm running windows 10

**Comment by TurBoss** [comment]
hello
I'm the responsible of the windows binaries
could you try this version instead?

https://mega.nz/#!1Yw0xbDD!ouA-KGce_x0hpXJBvspfoXv4qdjdeAEC3b2a8AFgkko

Thanks

**Comment by Xendergo** [comment]
I'm trying to render a 32x32 map, and I got this error:

PIL.Image.DecompressionBombError: Image size (268435456 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.

I think my image size is too big.

**Comment by TurBoss** [comment]
I hope this fixes

https://mega.nz/#!BNRhlSrJ!EAIB9cYhNxvdV1BpjsyfddleJDy2D1DDNPXat5A43h0

**Comment by Xendergo** [comment]
I got another error, it was this:

Converting to dds with the command:  nvdxt.exe -file temp\temp*.bmp -dxt1c -outsamedir -nmips 4 -Sinc -quality_highest
Creating minimap temp\mini.png using the command: nvdxt.exe -file temp\mini.png -dxt1c -nmips 9 -output temp/mini.dds -Sinc -quality_highest
Traceback (most recent call last):
  File "main.py", line 131, in <module>
  File "site-packages\gooey\python_bindings\gooey_decorator.py", line 89, in <lambda>
  File "main.py", line 127, in main
  File "smf_map_tools.py", line 535, in compileSMF
IOError: [Errno 2] No such file or directory: 'temp\\mini.dds'

I also noticed in the log it gave another error:

'nvdxt.exe' is not recognized as an internal or external command,
operable program or batch file.
'nvdxt.exe' is not recognized as an internal or external command,
operable program or batch file.

In case its helpful

**Comment by TurBoss** [comment]
oops my fault

please check this one I'm sure it works

https://mega.nz/#!oZwDBK4Z!vQQzn6TdqZ0SOab9bUebeNeZye5UVda0wh6CHSwz7XE

ty

**Comment by Xendergo** [comment]
It worked!

**Comment by TurBoss** [comment]
thanks!

**Comment by TurBoss** [comment]
@F4Tornado could this be closed?

**Comment by Xendergo** [comment]
Yes! I forgot!
